name: tugboat
version: 0.2.0
summary: CL tool for interacting with DigitalOcean droplets.
description: |
  A command line tool for interacting with your 
  DigitalOcean droplets.


grade: devel
confinement: devmode

apps:
  tugboat:
    command: usr/bin/ruby $SNAP/bin/tugboat
    environment:
      RUBYLIB: '$SNAP/usr/local/lib/site_ruby/2.3.0:$SNAP/usr/local/lib/x86_64-linux-gnu/site_ruby:$SNAP/usr/local/lib/site_ruby:$SNAP/usr/lib/ruby/vendor_ruby/2.3.0:$SNAP/usr/lib/x86_64-linux-gnu/ruby/vendor_ruby/2.3.0:$SNAP/usr/lib/ruby/vendor_ruby:$SNAP/usr/lib/ruby/2.3.0:$SNAP/usr/lib/x86_64-linux-gnu/ruby/2.3.0'     
      GEM_HOME: $SNAP/gems
      GEM_PATH: $SNAP 

parts:
  tugboat:
    source: https://github.com/petems/tugboat.git
    plugin: nil
    build: gem build tugboat.gemspec
    install: gem install tugboat-*.gem -i $SNAPCRAFT_PART_INSTALL
    build-packages: [gcc, make, libc6-dev, ruby-dev]
    stage-packages: [ruby]
    source-tag: v0.2.0

